sudo: required
language: ruby
services:
- docker
script:
- ls -lah
- docker build -f Dockerfile -t apsl/devpi .
- docker-compose up -d
- docker-compose ps
- sleep 20
- wget http://root:test@localhost:8000/
- cat index.html | grep "devpi-server"
notifications:
  email:
  - gshark@gmail.com
env:
  global:
  - DEVPI_VERSION=2.6.0
  - secure: lOBM35MLHejhYAn1sBkFAE6Abp6rxhjrblz4/VChdJJ/cXmXwc4kMbpuSRUSh4c4inHEPp0numsiL5EKJFXJp+5g+tpGg8LjvIieo6TQYWlAK0Ncr0TiFT95GZMWiQnJi34BalwA4ovZ2ZYaII0t9VXN28ltnA7GcmsPVcp46BgmZvpKgHV3j26ZR6d2og2AFtVgckUM2lhnTX+GhKyLlFVzLclDs7v59f7lpYU0s/h/WSkOyRnTwhEt1o5U+Yv+jnWjximYOEhadjN3kkQcoKJdis2ofAkZlL9avrW8NXWplLORK2ecAnfvTIOA7WvsP9xTawTIB96pbYb9l/xQmgELFMl4BT8MAyPJ3OCWv++lzjIT88RtkkdWwNmqoOvdLJB1OnypP1FDA5lRruwQ5ez9E7GRsKO3127tY2mxQ1i8lHiBOjTTsgVEEO+wSCAwtB8zs/r1krHTtAT8CcUCriOEgheV8jAIdUetEz7J8H+7skaUqBaDgyw9UFsNTfq4I9wjt2FlwBZtOZV/3KOJAT/QuyIl/Rd5A0UX3tYM0ysvxneoninbZHqydrrxMYH0O6hEi/7QHVrUyAnz4F3FcBo8R3vgsQcewTfeTllb3tBqENEDkhEJ2+7ILETHjBZd3PIox3ANsBKYOJhXRoE5/OcnB1NYjQCjHBJQis76qWI=
  - secure: GewN+ybd97/gHIpsFGy+oEbpVB+hvq02RsIZiEHi2RCNmk/kYde6H9LVdy9DKaCPd8jkFYuhzWjmV5awl4Jf0sqE2NgEN1Anmls4O6EYyIS511qWQO0Bn0KhBytS+ia5My6zexNdMQoe7yG//X10awbT39QKVtZzpbvKgkyGufScOuTKYJZjcNb78KB51t+jERm8vWV2LE3LyzqupUrg8cT8+aNtgTImONTPi3VrpSiFV8cVQpaipnPhbFvvz+bhECnqS9uaFtWnpnK9fW7jCtd+pvnqk4g5KzE+eONz74TdzwG6YWFu6kSOokD+NDz3vWXPE1QFT+DnvbK7f/Qi10brF9ojSdK4jUVYi3aN8X+rotH7bu51DZX6Uc2JnFNKhNhcJR5D+GCyKLVnurGES2J4X4jFcOquaFEBqyWyS0esYVc10hcC+vaDtWwrx2bZTrRtgs5VOT/GNJtMrAVYcRWa4MirRJsXyr3YyHU9LiNp/88Pm1zKvc297Z4o0+qSmHemT9y8uRZXuHuzKUR8gHBbvXZnNnOyeJC17JgJH9CKMM5VRTIkNNPE90M+r0pcycCuhkurYpr73WD5L6HWAQVAOOYbeHUnvfC4h212bzvX0yvFSSuree4rbNSZP2s5/ed5byIcBN6roWirK2UuL4Vpo6rKPTr5AnzLLen3nVI=
  - secure: bTU1wtlFbhAZmG4pL3BoU5WM0zaUqMqlUg9qiMgXIVcWGPrY7UGMdqdEeBOdD/IPNGwvtNH/G2DsT32tI7xuIBuZJiCPDYDQRa7VEwhfg/5mAq2dPwk3cYXOigXxGEbcmOsB3j+TdGqJFD44R7HFLAdAJAhDdHWGJTVH+BoaiIqDISedL/OllUSmQt8JTd/tzlMvSMyS83m+J0CBmlcPUyp3ryUzp7XtQeEr/ailB2/cQdiJcoNyqnox9KoOGB2iF95sNC1GAL9zlKMTjlhQ3idC6FhiByfi+1ANyVKj88Rcfy7UISYCpg9s4Ti51GGu1g6GvwmF+RN7gV1X8MYyvWZGXyo9c2dR2NmGksxI7a52fFrVWN+Pn+7EO2mbceUVN3MY1sJCcxcq3YZRJ/gCdKELzKl0YIR9WISdN1MFGOR9qm6nFK2EK6CMJ5hGdGZjV5/7b5xoPsmAZfcGGUlLhseRASbHrdeRtMRGQMRnTisUlQm0LWZ2fJN9Z+BxQyH7BEGp4pEYb/a6KkRgXFCwOEz9mytY3405d3pfrFKP12UgZ+NFkCXXYBw9rWiSdxS3p4/jB+gi3FuQXXCwf1TOafYsWvaQkiQnh1bXn3yp/GZT+jQF3iy1KCFP38RAZE2uSgzrsiMDZ9dFed+d4mieEPLrDGeUSil5whPo3fqeLZk=
after_success:
- docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $DEVPI_VERSION; fi`
- docker tag apsl/devpi apsl/devpi:$TAG
- docker push apsl/devpi:$TAG
 
